// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cMqTMbjEN8sArtqaz3w0hF_0YhYvp1E',
    appId: '1:967436725525:web:1ddf6c1db7b7b78cd90d1c',
    messagingSenderId: '967436725525',
    projectId: 'plantake-dr-cal',
    authDomain: 'plantake-dr-cal.firebaseapp.com',
    storageBucket: 'plantake-dr-cal.appspot.com',
    measurementId: 'G-NBPW8TS2SX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeyDYl7lU506NRLtf563GUK0WFA8esFOU',
    appId: '1:967436725525:ios:8ae7c9c903e08e6fd90d1c',
    messagingSenderId: '967436725525',
    projectId: 'plantake-dr-cal',
    storageBucket: 'plantake-dr-cal.appspot.com',
    androidClientId:
        '967436725525-acavsa4nsiun4elqjrsptj12rvj2mp3u.apps.googleusercontent.com',
    iosClientId:
        '967436725525-oh1oj5q7pkacq9ut42a818i23bvcjir4.apps.googleusercontent.com',
    iosBundleId: 'com.drcal.aicaloriecounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeyDYl7lU506NRLtf563GUK0WFA8esFOU',
    appId: '1:967436725525:ios:0854d499a0ae5c28d90d1c',
    messagingSenderId: '967436725525',
    projectId: 'plantake-dr-cal',
    storageBucket: 'plantake-dr-cal.appspot.com',
    androidClientId:
        '967436725525-acavsa4nsiun4elqjrsptj12rvj2mp3u.apps.googleusercontent.com',
    iosClientId:
        '967436725525-9jmjj371jcnvtqhr344vhmtnr7e053mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDrCal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuiy_-XzHWzgBKwAq7lMxfFv9jy38gwQ',
    appId: '1:1003578176360:android:2b178d3c6946b3e7681cdd',
    messagingSenderId: '1003578176360',
    projectId: 'test-4e0bb',
    databaseURL: 'https://test-4e0bb-default-rtdb.firebaseio.com',
    storageBucket: 'test-4e0bb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8cMqTMbjEN8sArtqaz3w0hF_0YhYvp1E',
    appId: '1:967436725525:web:5ebc7eabc39d4c7bd90d1c',
    messagingSenderId: '967436725525',
    projectId: 'plantake-dr-cal',
    authDomain: 'plantake-dr-cal.firebaseapp.com',
    storageBucket: 'plantake-dr-cal.appspot.com',
    measurementId: 'G-TFTD1JHVXD',
  );
}